# Generated by Django 4.2.6 on 2023-10-25 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_icecream_alter_kid_options_alter_kidparent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcecreamSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kid', verbose_name='Kid')),
                ('icecream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.icecream', verbose_name='Icecream')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
