# Generated by Django 4.2.6 on 2023-10-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_icecreamsale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreamshop',
            name='icecream',
            field=models.ManyToManyField(related_name='ice', to='main.icecream'),
        ),
    ]
