# Generated by Django 4.2.6 on 2023-10-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_icecreamshop_icecream'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidparent',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
